### ISSUE TITLE
Error: call of overloaded 'write(int)' is ambiguous

### ISSUE THREAD

**Issue by creadicted** [sebaJoSt/BlaeckSerial#1]
**Describe the bug**
Using the lib results in build errors. Is there a certain build flag or config needed?
 
**Hardware & Software (please complete the following information):**
- Arduino Board Nicla Sense 
 - BlaeckSerial Version  3.0.1
 - Arduino Software (IDE) Version 2.0.3
 - OS: Windows 10

**Comment by sebaJoSt** [comment]
Hey @creadicted , the library was programmed for avr architecture and tested with Arduino Uno and Mega. 
However I made some minor changes to fix the compiler errors. Please extract the file and replace it in the Arduino libraries folder (libraries -> BlaeckSerial -> src) and let me know if it works for you.

[BlaeckSerial.cpp.zip](https://github.com/sebaJoSt/BlaeckSerial/files/10540482/BlaeckSerial.cpp.zip)
